# Generated by Django 5.0.4 on 2024-04-26 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='E_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('pin', models.CharField(default=0, max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('reverse', 'Reverse')], default='pending')),
                ('paymentType', models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer')], default=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletApp.e_wallet')),
            ],
        ),
    ]
